name: Notify Main Repo

on:
  push:
    branches:
      - main  # или ветка, в которой нужно отслеживать изменения

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger main repo update
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
        https://api.github.com/repos/juhc/monopoly4u/dispatches \
        -d '{"event_type":"update-submodule"}'
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
